[toolchain]

[features]
seeds = true
skip-lint = false

[programs.localnet]
backend = "6Dz1KhuyqPKh4MmVjsNXKY12BuihenzcHM6jfwd8jMSG"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/mnt/c/Users/THANHPHAT/Documents/solana_TEEN_TITANS/solana_key/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
