[toolchain]

[features]
seeds = true
skip-lint = false

[programs.localnet]
backend = "9PCZFZ1gd2g9q5zUaKtaDs14TVGyBhiLeS6DZtF1g9ZC"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/learner123/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
